### ISSUE TITLE
[BigQuery] Is there a way to specify QueryResultOptions from query()

### ISSUE THREAD

**Issue by dclements** [googleapis/google-cloud-java#3108] opened 2018-03-29 20:27 UTC
Sometime after 0.32.0-beta the method of querying changed such that it is no longer obvious that there is a way to specify either `QueryResultsOption.maxWaitTime` or `QueryResultsOption.pageSize` when using `BigQuery.query`. All of the examples seem to use `BigQuery.query` but none seem to cover the case of controlling the page sizes or altering the timeouts. 

Is there a way to do this now?

**Comment by pongad** [comment] 2018-04-10 17:48
Hmm, that change might have been a mistake.
However, you should be able to do `bigquery.create(queryJobConfiguration).getQueryResults(QueryResultsOption.pageSize(n))`

I'll take this as a feature request to document tis.

**Comment by pongad** [comment] 2018-08-13 23:42
@macadelsol Can you give more details about what you're seeing vs expecting?

We have a test that should ensure setting pagesize by `getQueryResults` work.
To make sure I actually inserted
```java
System.err.println(bigquery
          .tabledata()
          .list(projectId, datasetId, tableId)
          .setMaxResults(Option.MAX_RESULTS.getLong(options))
          .setPageToken(Option.PAGE_TOKEN.getString(options))
          .setStartIndex(
              Option.START_INDEX.getLong(options) != null
                  ? BigInteger.valueOf(Option.START_INDEX.getLong(options))
                  : null));
```
on [this line](https://github.com/GoogleCloudPlatform/google-cloud-java/blob/27c90f1298bb27a618ff59b3cd17321c577f3a6b/google-cloud-clients/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/spi/v2/HttpBigQueryRpc.java#L295) effectively printing out the request we're sending to bigquery service.

When I set `n=2`, I got `{datasetId=XXX, maxResults=2, projectId=YYY, tableId=ZZZ}` which is expected.

**Comment by macadelsol** [comment] 2018-08-14 04:05
Hello! ty for replying,

My code is as follows:
`
       
        JobId jobId = JobId.of(UUID.randomUUID().toString());
        
        queryJob = bigquery.create(JobInfo.newBuilder(queryConfig).setJobId(jobId).build());

        queryJob = queryJob.waitFor();
        
        TableResult page = queryJob.getQueryResults(BigQuery.QueryResultsOption.pageSize(9999L) ;
`

Thats for executing, and getting the first page, and for getting each next page: 

`
    

    page = queryJob.getQueryResults(BigQuery.QueryResultsOption.pageToken(page.getNextPageToken()),BigQuery.QueryResultsOption.pageSize(Long.parseLong(9999L)));
    for (FieldValueList row : page.getValues()) {
    ...
    }
`
                       


This works for around 15 million registers, in which after it fails and I get and exception about BQ cant find table (the page table), it never respects the page size of 9999.

Any ideas??
ty in advance

**Comment by pongad** [comment] 2018-08-14 18:10
@tswast Do you have any ideas about BQ not being to find the table? @macadelsol Can you share a stack trace with us?

> it never respects the page size of 9999

I'm sorry I'm still not sure what unexpected behavior you're seeing. Setting page size to 9999 means we're asking for at most 9999 rows at a time. It's possible that the response is too large that BQ decides to send fewer rows. I don't think there's much a client lib can do. Are you seeing each page containing more than 9999 rows? That'd be a cause for concern. I can't reproduce this but it's possible the server is doing something funny.

**Comment by tswast** [comment] 2018-08-14 19:25
> Setting page size to 9999 means we're asking for at most 9999 rows at a time. It's possible that the response is too large that BQ decides to send fewer rows.

Yes, this is expected. I recall the maximum page size is somewhere in the order of 10 megabytes.

> I get and exception about BQ cant find table (the page table).

You get this exception some time after the first page? Can you share the exception?

**Comment by sduskis** [comment] 2018-11-30 15:34
@dclements, I'm closing this issue, since we didn't get a response.  We'd be happy to reopen this issue once we have more information.

**Closed by sduskis** 2018-11-30 15:34 UTC
Labels: api: bigquery, documentation, type: docs, type: feature request
