### ISSUE TITLE
PERMISSION_DENIED for google service account

### ISSUE THREAD

**Issue by agzamovr** [googleapis/google-cloud-java#3083] opened 2018-03-26 13:28 UTC
I've successfully subscribed to Pub?Sub service under my own user account. Howewer when i set **GOOGLE_APPLICATION_CREDENTIALS** env variable to point service account key file i got permission denied exception. This service account has `Pub/Sub Admin` role. Here is stack trace of exception:
```
SEVERE: terminated streaming with exception
com.google.api.gax.rpc.PermissionDeniedException: io.grpc.StatusRuntimeException: PERMISSION_DENIED: User not authorized to perform this action.
	at com.google.api.gax.rpc.ApiExceptionFactory.createException(ApiExceptionFactory.java:55)
	at com.google.cloud.pubsub.v1.StreamingSubscriberConnection$1.onFailure(StreamingSubscriberConnection.java:237)
	at com.google.common.util.concurrent.Futures$4.run(Futures.java:1123)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:435)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:900)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:811)
	at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:675)
	at com.google.common.util.concurrent.SettableFuture.setException(SettableFuture.java:53)
	at com.google.cloud.pubsub.v1.StreamingSubscriberConnection$StreamingPullResponseObserver.onError(StreamingSubscriberConnection.java:173)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:419)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:41)
	at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:684)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:41)
	at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:392)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:475)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:63)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:557)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:478)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:590)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: io.grpc.StatusRuntimeException: PERMISSION_DENIED: User not authorized to perform this action.
	at io.grpc.Status.asRuntimeException(Status.java:526)
	... 19 more
```

**Comment by PrashSi** [comment] 2018-04-20 10:54
I am also facing the same problem in production and with selective hosts. I am using the same JSON(service account credentials) on 30 different hosts and 3 of them have reported this error. This is a runtime error with a generic message. Please suggest a way to debug it.

**Comment by sangamangreg** [comment] 2018-04-23 12:11
I am also facing the same issue. Are you able to solve this?

**Comment by agzamovr** [comment] 2018-04-23 14:46
No, we have decided to use RabbitMQ instead.

**Comment by muzuro** [comment] 2018-05-10 11:05
We have same issue, weird that some messages is received - some failed

**Comment by Greenbones** [comment] 2018-05-15 17:39
Same problem here. 

The publish role isn't sufficient to publish. The Subscriber role isn't sufficient to subscribe. Even the pub sub admin role isn't sufficient to publish or subscribe.

The only way we've been able to get this working is to use a service account with the owner role, which is obviously not acceptable.

There's clearly a privilege missing from all those pub sub roles. Even if this bug isn't going to get addressed, could we at least find out what privilege it is so we can create custom roles for pub sub that don't have all 1407 privileges on them like the Owner does?

**Comment by pongad** [comment] 2018-05-23 20:58
This sounds bad. Am I understanding correctly that this issue is intermittent? Our authentication lib has to refresh credentials every hour or so. I suspect that the bug could creep in there.

**Comment by PrashSi** [comment] 2018-05-24 09:28
@vchudnov-g  Single host sometimes succeeds and sometimes fails. We have also observed that only these 4 to 5 hosts which are ideal(haven't published a single message)for a day or more throws this exception. So maybe there is a problem in refreshing the credentials?

**Comment by hzyi-google** [comment] 2018-05-30 23:48
@PrashSi Am I understanding correctly that the failure is on the subscriber side and happens intermittently during streaming calls (pulling messages)? 
Also are you running on any Google Cloud machines(GCE, GAE, GKE) or local machines?

**Comment by hzyi-google** [comment] 2018-05-31 00:01
Also, it would be great if any of you could do the following to help debug if you have cloud-debugger available:

> set a watch point in [OAuth2Credentials::shouldRefresh](https://github.com/google/google-auth-library-java/blob/ab2110490efcb0cdd6ebb6dde3b07c5fca89711d/oauth2_http/java/com/google/auth/oauth2/OAuth2Credentials.java#L194) and log anytime expiresIn < 5000L

**Comment by PrashSi** [comment] 2018-06-04 10:53
@hzyi-google Running on local machines.

**Comment by hzyi-google** [comment] 2018-06-06 17:56
I had a publisher and a few subscribers set up on my local machine and had them running for about 12 hours but could not reproduce this problem. The publisher publishes every 2 seconds. Anything different I can do to help increase the frequency of the bug?

**Comment by pimotte** [comment] 2018-07-04 07:45
I have observed this issue once in the following situation:
- Spring boot application
- Running in Google Container Engine
- Application listening to 6 subscriptions
- One of the subscribers stopped with this error about 4 days and 9 hours after launching the application
- Between the application starting and the error occurring 1 message was published to a topic not connected to the erroneous subscription, no other messages were published.
- Dependencies from the google-cloud-bom version 0.49.0-alpha

**Comment by ejgutierrezvega** [comment] 2018-08-03 01:03
Same issue trying to use Stackdriver exporter.

```io.opencensus.exporter.stats.stackdriver.StackdriverExporterWorker export
WARNING: ApiException thrown when exporting TimeSeries.
com.google.api.gax.rpc.PermissionDeniedException: io.grpc.StatusRuntimeException: PERMISSION_DENIED: The caller does not have permission
at com.google.api.gax.rpc.ApiExceptionFactory.createException(ApiExceptionFactory.java:55)
at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:72)
at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:60)
at com.google.api.gax.grpc.GrpcExceptionCallable$ExceptionTransformingFuture.onFailure(GrpcExceptionCallable.java:95)
at com.google.api.core.ApiFutures$1.onFailure(ApiFutures.java:61)
at com.google.common.util.concurrent.Futures$4.run(Futures.java:1123)
at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:435)
at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:900)
at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:811)
at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:675)
at io.grpc.stub.ClientCalls$GrpcFuture.setException(ClientCalls.java:492)
at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:467)
at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:684)
at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:391)
at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:471)
at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:63)
at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:553)
at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:474)
at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:591)
at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)```

**Comment by ejgutierrezvega** [comment] 2018-08-03 20:36
I was able to make it work following the instructions from:
[https://github.com/census-instrumentation/opencensus-java/tree/master/exporters/stats/stackdriver#quickstart]()

Specifically enabling billing to my gcp account.

**Comment by JustinBeckwith** [comment] 2018-09-13 18:18
@hzyi-google this one looks a tad scary.  Are you able to actively look at this?

**Comment by hzyi-google** [comment] 2018-09-13 19:09
@JustinBeckwith I've been trying to repro this but without any luck. I've been talking with Customer Solution Engineers to see if they can get more information from customers but didn't get anything useful. Could you help escalate this?

**Comment by chingor13** [comment] 2018-12-05 00:12
This issue appears to have diverged into a few scenarios:
* Running locally never succeeded
* Running on GCE without billing enabled

Closing this out and we can open a new issue with additional repro steps if it's still occurring.

**Closed by chingor13** 2018-12-05 00:12 UTC
Labels: api: pubsub, auth, type: question

**Comment by lucianosouzabobsin** [comment] 2020-06-24 12:49
Fecharam e não falaram nada com nada? 

> This issue appears to have diverged into a few scenarios:
> 
> * Running locally never succeeded
> * Running on GCE without billing enabled
> 
> Closing this out and we can open a new issue with additional repro steps if it's still occurring.

Resolved?

**Comment by prodev0329** [comment] 2021-12-19 13:55
I've got the same error.
To solve the error, please reference the following link.
https://cloud.google.com/iam/docs/permissions-reference

**Comment by surajjha-dev** [comment] 2022-01-28 06:04
If you are using GCP service on Compute Engine then you need to provide Credentials explicitly to Publisher Class, faced the same issue this worked for me.			

CredentialsProvider credentialsProvider =
				    FixedCredentialsProvider.create(
				  ServiceAccountCredentials.fromStream(PubSubUtil.class.getClassLoader().getResourceAsStream("key.json")));

**Comment by Sanoojkoloth** [comment] 2023-03-28 16:17
I got the same issue. 
For me locally it is working with my credentials and when I started to pass the default credential from VM, it started to fail with above error

**Comment by cyril-telr** [comment] 2025-11-18 05:28
hi i have now the same issue in DEV and locally
