### ISSUE TITLE
Can not add Enable billing for Project (Cloud API)

### ISSUE THREAD

**Issue by Thien658jjh** [googleapis/google-cloud-java#3776] opened 2018-10-05 11:31 UTC
I got this Error when I wanted to add payment method : 
### Unable to complete transaction: prepaid cards can't be used

Why is that ?

**Comment by chingor13** [comment] 2018-10-08 16:29
This policy is dictated by Google Cloud Platform as a whole. See https://cloud.google.com/billing/docs/how-to/payment-methods. If you have further questions about this, please [contact GCP support](https://support.google.com/cloud).

Closing this out as it is not caused by the java libraries.

**Closed by chingor13** 2018-10-08 16:29 UTC
Labels: type: question
