### ISSUE TITLE
Quick start guide ends with NoSuchMethod error

### ISSUE THREAD

**Issue by Rodolfo-Bevione** [googleapis/google-cloud-java#4019] opened 2018-11-19 21:34 UTC
I'm trying to create an API which, when triggered, sends a request to Dialogflow.
To do that, I'm using the Java SDK, as found [here](https://github.com/googleapis/google-cloud-java/tree/master/google-cloud-clients/google-cloud-dialogflow).

The problematic code snippet is copy-pasted from [here](https://googleapis.github.io/google-cloud-java/google-cloud-clients/apidocs/index.html?com/google/cloud/dialogflow/v2beta1/package-summary.html), to the bottom of the page.

```
try (SessionsClient sessionsClient = SessionsClient.create()) {
    SessionName session = SessionName.of(genericProjectId, genericSessionId);
    QueryInput queryInput = QueryInput.newBuilder().build();
    DetectIntentResponse response = sessionsClient.detectIntent(session, 
    queryInput);
}
```
When I run "SessionsClient.create()", the error

```
javax.ejb.TransactionRolledbackLocalException: Exception thrown from bean: java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkArgument(ZLjava/lang/String;CLjava/lang/Object;)V
```
is thrown at runtime. Knowing this has something to do with either guava or protobuf, I have trimmed down everything from my pom.xml file, so that the only libraries loaded are those from the SDK. That's the current POM.
```
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.mycompany</groupId>
    <artifactId>MYPROJECTNAME</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>war</packaging>
    <!--START EDIT 1: ADDED AS A TEST-->
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.google.cloud</groupId>
                <artifactId>google-cloud-bom</artifactId>
                <version>0.71.0-alpha</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
    <!--END EDIT 1-->
    <dependencies>
        <dependency>
            <groupId>com.google.cloud</groupId>
            <artifactId>google-cloud-dialogflow</artifactId>
            <version>0.71.0-alpha</version>
        </dependency>
        <dependency>
            <groupId>javax</groupId>
            <artifactId>javaee-api</artifactId>
            <version>7.0</version>
            <scope>provided</scope>
        </dependency>
    </dependencies>
    <build>
        <finalName>MYPROJECTNAME</finalName>
        <plugins>
        </plugins>
    </build>
    <properties>
        <maven.compiler.source>1.8</maven.compiler.source>
        <maven.compiler.target>1.8</maven.compiler.target>
        <failOnMissingWebXml>false</failOnMissingWebXml>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <projectId>MYPROJECTID</projectId>
    </properties>
</project>
```
Running mvn depenceny:tree doesn't show any problems, and by opening the WAR archive created I can't see any duplicate library. Below is the verbose dependency tree
```
+- com.google.cloud:google-cloud-dialogflow:jar:0.71.0-alpha:compile
|  +- com.google.cloud:google-cloud-core:jar:1.53.0:compile
|  |  +- com.google.guava:guava:jar:26.0-android:compile
|  |  |  +- (com.google.code.findbugs:jsr305:jar:3.0.2:compile - omitted for duplicate)
|  |  |  +- org.checkerframework:checker-compat-qual:jar:2.5.2:compile
|  |  |  +- com.google.errorprone:error_prone_annotations:jar:2.1.3:compile
|  |  |  +- com.google.j2objc:j2objc-annotations:jar:1.1:compile
|  |  |  \- org.codehaus.mojo:animal-sniffer-annotations:jar:1.14:compile
|  |  +- joda-time:joda-time:jar:2.9.2:compile
|  |  +- com.google.http-client:google-http-client:jar:1.27.0:compile
|  |  |  +- (com.google.guava:guava:jar:20.0:compile - omitted for conflict with 26.0-android)
|  |  |  +- org.apache.httpcomponents:httpclient:jar:4.5.5:compile
|  |  |  |  +- org.apache.httpcomponents:httpcore:jar:4.4.9:compile
|  |  |  |  +- commons-logging:commons-logging:jar:1.2:compile
|  |  |  |  \- commons-codec:commons-codec:jar:1.10:compile
|  |  |  \- (com.google.j2objc:j2objc-annotations:jar:1.1:compile - omitted for duplicate)
|  |  +- com.google.code.findbugs:jsr305:jar:3.0.2:compile
|  |  +- com.google.api:api-common:jar:1.7.0:compile
|  |  |  +- (com.google.code.findbugs:jsr305:jar:3.0.2:compile - omitted for duplicate)
|  |  |  \- (com.google.guava:guava:jar:19.0:compile - omitted for conflict with 26.0-android)
|  |  +- com.google.api:gax:jar:1.35.0:compile
|  |  |  +- (com.google.guava:guava:jar:26.0-android:compile - omitted for duplicate)
|  |  |  +- (com.google.code.findbugs:jsr305:jar:3.0.2:compile - omitted for duplicate)
|  |  |  +- org.threeten:threetenbp:jar:1.3.3:compile
|  |  |  +- com.google.auth:google-auth-library-oauth2-http:jar:0.11.0:compile
|  |  |  |  +- (com.google.auth:google-auth-library-credentials:jar:0.11.0:compile - omitted for conflict with 0.12.0)
|  |  |  |  +- (com.google.http-client:google-http-client:jar:1.24.1:compile - omitted for conflict with 1.27.0)
|  |  |  |  +- com.google.http-client:google-http-client-jackson2:jar:1.24.1:compile
|  |  |  |  |  +- (com.google.http-client:google-http-client:jar:1.24.1:compile - omitted for conflict with 1.27.0)
|  |  |  |  |  \- com.fasterxml.jackson.core:jackson-core:jar:2.9.2:compile
|  |  |  |  \- (com.google.guava:guava:jar:20.0:compile - omitted for conflict with 26.0-android)
|  |  |  \- (com.google.api:api-common:jar:1.7.0:compile - omitted for duplicate)
|  |  +- com.google.protobuf:protobuf-java-util:jar:3.6.1:compile
|  |  |  +- (com.google.protobuf:protobuf-java:jar:3.6.1:compile - omitted for duplicate)
|  |  |  +- (com.google.guava:guava:jar:19.0:compile - omitted for conflict with 26.0-android)
|  |  |  \- com.google.code.gson:gson:jar:2.7:compile
|  |  +- com.google.api.grpc:proto-google-common-protos:jar:1.12.0:compile
|  |  |  \- (com.google.protobuf:protobuf-java:jar:3.5.1:compile - omitted for conflict with 3.6.1)
|  |  \- com.google.api.grpc:proto-google-iam-v1:jar:0.12.0:compile
|  |     +- (com.google.protobuf:protobuf-java:jar:3.5.1:compile - omitted for conflict with 3.6.1)
|  |     +- (com.google.api:api-common:jar:1.7.0:compile - version managed from 1.5.0; omitted for duplicate)
|  |     \- (com.google.api.grpc:proto-google-common-protos:jar:1.12.0:compile - version managed from 1.11.0; omitted for duplicate)
|  +- com.google.cloud:google-cloud-core-grpc:jar:1.53.0:compile
|  |  +- com.google.auth:google-auth-library-credentials:jar:0.12.0:compile
|  |  +- (com.google.cloud:google-cloud-core:jar:1.53.0:compile - omitted for duplicate)
|  |  +- (com.google.guava:guava:jar:26.0-android:compile - omitted for duplicate)
|  |  +- com.google.protobuf:protobuf-java:jar:3.6.1:compile
|  |  +- (com.google.protobuf:protobuf-java-util:jar:3.6.1:compile - omitted for duplicate)
|  |  +- io.grpc:grpc-protobuf:jar:1.16.1:compile
|  |  |  +- (io.grpc:grpc-core:jar:1.16.1:compile - omitted for duplicate)
|  |  |  +- (com.google.protobuf:protobuf-java:jar:3.5.1:compile - omitted for conflict with 3.6.1)
|  |  |  +- (com.google.guava:guava:jar:26.0-android:compile - omitted for duplicate)
|  |  |  +- (com.google.api.grpc:proto-google-common-protos:jar:1.12.0:compile - version managed from 1.0.0; omitted for duplicate)
|  |  |  \- io.grpc:grpc-protobuf-lite:jar:1.16.1:compile
|  |  |     +- (io.grpc:grpc-core:jar:1.16.1:compile - omitted for duplicate)
|  |  |     \- (com.google.guava:guava:jar:26.0-android:compile - omitted for duplicate)
|  |  +- io.grpc:grpc-context:jar:1.16.1:compile
|  |  +- (io.grpc:grpc-netty-shaded:jar:1.16.1:compile - omitted for duplicate)
|  |  +- (io.grpc:grpc-stub:jar:1.16.1:compile - omitted for duplicate)
|  |  +- (io.grpc:grpc-auth:jar:1.16.1:compile - omitted for duplicate)
|  |  \- com.google.api:gax-grpc:jar:1.35.0:compile
|  |     +- (com.google.api:gax:jar:1.35.0:compile - omitted for duplicate)
|  |     +- (io.grpc:grpc-stub:jar:1.16.1:compile - omitted for duplicate)
|  |     +- (io.grpc:grpc-auth:jar:1.16.1:compile - omitted for duplicate)
|  |     +- (io.grpc:grpc-protobuf:jar:1.16.1:compile - omitted for duplicate)
|  |     +- (com.google.guava:guava:jar:26.0-android:compile - omitted for duplicate)
|  |     +- (com.google.code.findbugs:jsr305:jar:3.0.2:compile - omitted for duplicate)
|  |     +- (org.threeten:threetenbp:jar:1.3.3:compile - omitted for duplicate)
|  |     +- (com.google.auth:google-auth-library-oauth2-http:jar:0.11.0:compile - omitted for duplicate)
|  |     +- (com.google.auth:google-auth-library-credentials:jar:0.11.0:compile - omitted for conflict with 0.12.0)
|  |     +- (com.google.api.grpc:proto-google-common-protos:jar:1.12.0:compile - version managed from 1.0.0; omitted for duplicate)
|  |     +- (com.google.api:api-common:jar:1.7.0:compile - version managed from 1.5.0; omitted for duplicate)
|  |     \- (io.grpc:grpc-netty-shaded:jar:1.16.1:compile - omitted for duplicate)
|  +- com.google.api.grpc:proto-google-cloud-dialogflow-v2beta1:jar:0.36.0:compile
|  |  +- (com.google.protobuf:protobuf-java:jar:3.6.1:compile - omitted for duplicate)
|  |  +- (com.google.api:api-common:jar:1.7.0:compile - version managed from 1.5.0; omitted for duplicate)
|  |  \- (com.google.api.grpc:proto-google-common-protos:jar:1.12.0:compile - version managed from 1.0.0; omitted for duplicate)
|  +- com.google.api.grpc:proto-google-cloud-dialogflow-v2:jar:0.36.0:compile
|  |  +- (com.google.protobuf:protobuf-java:jar:3.6.1:compile - omitted for duplicate)
|  |  +- (com.google.api:api-common:jar:1.7.0:compile - version managed from 1.5.0; omitted for duplicate)
|  |  \- (com.google.api.grpc:proto-google-common-protos:jar:1.12.0:compile - version managed from 1.0.0; omitted for duplicate)
|  +- io.grpc:grpc-netty-shaded:jar:1.16.1:compile
|  |  \- (io.grpc:grpc-core:jar:1.16.1:compile - scope updated from runtime; omitted for duplicate)
|  +- io.grpc:grpc-stub:jar:1.16.1:compile
|  |  \- io.grpc:grpc-core:jar:1.16.1:compile
|  |     +- (io.grpc:grpc-context:jar:1.16.1:compile - omitted for duplicate)
|  |     +- (com.google.code.gson:gson:jar:2.7:compile - omitted for duplicate)
|  |     +- (com.google.errorprone:error_prone_annotations:jar:2.2.0:compile - omitted for conflict with 2.1.3)
|  |     +- (com.google.code.findbugs:jsr305:jar:3.0.2:compile - omitted for duplicate)
|  |     +- (org.codehaus.mojo:animal-sniffer-annotations:jar:1.17:compile - omitted for conflict with 1.14)
|  |     +- (com.google.guava:guava:jar:26.0-android:compile - omitted for duplicate)
|  |     +- io.opencensus:opencensus-api:jar:0.12.3:compile
|  |     |  \- (com.google.errorprone:error_prone_annotations:jar:2.2.0:compile - omitted for conflict with 2.1.3)
|  |     \- io.opencensus:opencensus-contrib-grpc-metrics:jar:0.12.3:compile
|  |        +- (com.google.errorprone:error_prone_annotations:jar:2.2.0:compile - omitted for conflict with 2.1.3)
|  |        \- (io.opencensus:opencensus-api:jar:0.12.3:compile - omitted for duplicate)
|  \- io.grpc:grpc-auth:jar:1.16.1:compile
|     +- (io.grpc:grpc-core:jar:1.16.1:compile - omitted for duplicate)
|     \- (com.google.auth:google-auth-library-credentials:jar:0.9.0:compile - omitted for conflict with 0.12.0)
\- javax:javaee-api:jar:7.0:provided
   \- com.sun.mail:javax.mail:jar:1.5.0:provided
      \- javax.activation:activation:jar:1.1:provided
```

Tried compiling both with NetBeans and by command line, the problem still persists.
As per the [troubleshooting guide](https://github.com/googleapis/google-cloud-java/blob/master/TROUBLESHOOTING.md) I have tried using the maven shade plugin, with no success. Tried also referencing in the pom all the possible versions of Guava from 20.0 onward, but the error still persist.

Thanks in advance

#### Environment details

- OS: Windows 10
- Java version: 8
- google-cloud-java version(s): 0.7.1
- Server: Payara 5.183
- Endpoints: developed with JAX-RS

#### Stacktrace
```
java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkArgument(ZLjava/lang/String;CLjava/lang/Object;)V
	at io.grpc.Metadata$Key.validateName(Metadata.java:628)
	at io.grpc.Metadata$Key.<init>(Metadata.java:636)
	at io.grpc.Metadata$Key.<init>(Metadata.java:566)
	at io.grpc.Metadata$AsciiKey.<init>(Metadata.java:740)
	at io.grpc.Metadata$AsciiKey.<init>(Metadata.java:735)
	at io.grpc.Metadata$Key.of(Metadata.java:592)
	at io.grpc.Metadata$Key.of(Metadata.java:588)
	at com.google.api.gax.grpc.GrpcHeaderInterceptor.<init>(GrpcHeaderInterceptor.java:61)
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.createSingleChannel(InstantiatingGrpcChannelProvider.java:176)
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.createChannel(InstantiatingGrpcChannelProvider.java:160)
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.getTransportChannel(InstantiatingGrpcChannelProvider.java:152)
	at com.google.api.gax.rpc.ClientContext.create(ClientContext.java:149)
	at com.google.cloud.dialogflow.v2.stub.GrpcSessionsStub.create(GrpcSessionsStub.java:75)
	at com.google.cloud.dialogflow.v2.stub.SessionsStubSettings.createStub(SessionsStubSettings.java:100)
	at com.google.cloud.dialogflow.v2.SessionsClient.<init>(SessionsClient.java:132)
	at com.google.cloud.dialogflow.v2.SessionsClient.create(SessionsClient.java:114)
	at com.google.cloud.dialogflow.v2.SessionsClient.create(SessionsClient.java:106)
```

**Comment by elharo** [comment] 2018-11-21 17:41
There is no  com.google.common.base.Preconditions.checkArgument(ZLjava/lang/String;CLjava/lang/Object;)V in any version o Guava I'm familiar with. The first argument to checkArgument is always a boolean, so far as I know. Now the question becomes, where's the code that's actually trying to call that non-existent method?

**Comment by eamonnmcmanus** [comment] 2018-11-21 20:20
That signature decodes to void checkArgument(boolean, String, char, Object) which exists in Guava 20 but not in Guava 19. So I think the issue is with the Guava 19 that appears twice in the dependency tree.

**Comment by elharo** [comment] 2018-11-21 20:34
OK, then it's almost certainly a diamond dependency problem. Adding a direct dependency on Guava 20 should cure it.

Also, Z means boolean? Need to brush up on my byte code.

**Comment by eamonnmcmanus** [comment] 2018-11-21 20:46
Only one of `byte` and `boolean` could get the letter B. :-) I suppose Z was as good as any other letter. On the other hand, the reason L had to mean class reference, so `long` has to use J, is lost to the mists of time.
[ref](https://docs.oracle.com/javase/specs/jvms/se8/html/jvms-4.html#jvms-4.3.2)

**Comment by smallufo** [comment] 2019-02-03 16:07
I am facing the same problem with `io.grpc:grpc-protobuf:jar:1.18.0` , I am sure the whole mvn dependencies don't contain any old guava. But I finally found an groovy script which `@Grab` a guava v19 , which leads intelliJ to load the old guava and pops the error. The whole problem is invisible in the mvn dependency tree. 

So , maybe you should check if you have any groovy scripts `Grabbing` old guava libs.

**Comment by athakor** [comment] 2019-09-19 09:57
@Rodolfo-Bevione I have created simple  JAX-RS example with all your GCP dependencies and try to reproduce it but unable to reproduce it.its working fine below are the code snippet,endpoint and response. 

**Server:**
Payara Server 5 (5.193)

**Code snippest:**
```
@Path("/createsession")
public class DialogflowService {
  
  @GET
  @Produces(MediaType.TEXT_PLAIN)
  public String createSession() throws Exception{
    String genericProjectId = ServiceOptions.getDefaultProjectId();
    String genericSessionId = UUID.randomUUID().toString();
    DetectIntentResponse response = null;
    try (SessionsClient sessionsClient = SessionsClient.create()) {
      SessionName session = SessionName.of(genericProjectId, genericSessionId);
      TextInput.Builder textInput = TextInput.newBuilder().setText("hi").setLanguageCode("en-US");
      QueryInput queryInput = QueryInput.newBuilder().setText(textInput).build();
      response = sessionsClient.detectIntent(session, queryInput);
    }
    return response.toString();
  }

}
```

**Endpoint:**
http://localhost:8080/***/rest/createsession

**Response:**
```
response_id: "cc03099c-4251-466e-92ad-85942ea661b8-f308a5c4"
query_result {
  query_text: "hi"
  action: "input.welcome"
  parameters {
  }
  all_required_params_present: true
  fulfillment_text: "Greetings! How can I assist?"
  fulfillment_messages {
    text {
      text: "Greetings! How can I assist?"
    }
  }
  intent {
    name: "projects/cloud-test-project-252710/agent/intents/c517cfb8-b223-4437-b00f-1f51af01c2f1"
    display_name: "Default Welcome Intent"
  }
  intent_detection_confidence: 1.0
  language_code: "en"
}
```

**Comment by athakor** [comment] 2019-09-27 16:15
Closing this issue due to stalness feel free to reopen it if you face.

**Closed by athakor** 2019-09-27 16:15 UTC
Labels: api: dialogflow, dependencies, type: question
