### ISSUE TITLE
Logging Appender Error Reporting - Services/Versions in GKE

### ISSUE THREAD

**Issue by hkothari** [googleapis/google-cloud-java#5694] opened 2019-07-06 14:08 UTC
I use the Logback Appender with error reporting in my code, which runs on GKE. One thing I've been trying to do is get the errors to include the necessary metadata to use the "Services" filter in the error reporting console, right now if I filter here all I can see is "gke_instances"

From what I can tell this metadata does not comes from the log messages themselves because the log payloads look like the following and it doesn't include the string "gke_instances" anywhere:

```
{
 insertId:  "1oi23bcfgdthmk"  
 labels: {…}  
 logName:  "projects/my-project/logs/service-name"  
 receiveTimestamp:  "2019-07-05T21:00:14.646532228Z"  
 resource: {
  labels: {
   cluster_name:  "my-staging-cluster"    
   container_name:  ""    
   instance_id:  "1234567"    
   namespace_id:  ""    
   pod_id:  "service-name-rest-staging-587dd98d4-lbcjn"    
   project_id:  "my-project"    
   zone:  "us-central1-a"    
  }
  type:  "container"   
 }
 severity:  "ERROR"  
 textPayload:  "Error handling a request: 00dda7db7292a37f
java.lang.IllegalStateException: Some exception
    ...
    at java.base/java.lang.Thread.run(Thread.java:834)"  
 timestamp:  "2019-07-05T21:00:14.551Z"  
}
```

Any idea how I can configure the logback appender to customize this information to disambiguate between my own services?

**Comment by pmakani** [comment] 2019-07-19 07:53
@hkothari I tested logging appender using container,
For MoniterResource labels, please refer this link https://cloud.google.com/logging/docs/api/v2/resource-list, 
Till now MoniterResource supports labels present in the resource-list so you refer can set respective label accordingly. 
If you want to configure your custom labels inside log, you can do that by setting label using LogEntry Builder.
  ```
    LoggingOptions options = LoggingOptions.getDefaultInstance();
    Logging logging = options.getService();
    LogEntry firstEntry =
        LogEntry.newBuilder(Payload.StringPayload.of("message"))
            .setLogName("test-log")
            .setResource(
                MonitoredResource.newBuilder("container")
                    .addLabel("project_id", options.getProjectId())
                    .build())
            .addLabel("my-custom-label", "App-and-version")
            .setSeverity(Severity.ERROR)
            .build();
    logging.write(Collections.singleton(firstEntry));
```

After this, it will show you your custom labels in log entries.

**Comment by hkothari** [comment] 2019-07-19 12:47
Thanks @pmakani I think what I was trying to get as was, what do I need to set to be able to set the service name to show up in the error reporting:
![screen](https://user-images.githubusercontent.com/297902/61536064-bf23e280-aa01-11e9-94ed-6deee120d59f.png)
 
I can successfully filter for it to show up in logs, and have no issues there but for error reporting it just shows "gke_services"

**Comment by pmakani** [comment] 2019-08-09 05:02
@hkothari if you want to use custom error reporting service, you can use below sample code.

        
        String projectId = ServiceOptions.getDefaultProjectId();
        ProjectName projectName = ProjectName.of(projectId);
        try (ReportErrorsServiceClient reportErrorsServiceClient = ReportErrorsServiceClient.create()) {
            // Custom error events require an error reporting location as well.
            ErrorContext errorContext = ErrorContext.newBuilder()
                    .setReportLocation(SourceLocation.newBuilder()
                            .setFilePath("Test.java")
                            .setLineNumber(10)
                            .setFunctionName("myMethod")
                            .build())
                    .build();

            //Report a custom error event
            ReportedErrorEvent customErrorEvent = ReportedErrorEvent.getDefaultInstance()
                    .toBuilder()
                    .setMessage("custom error event")
                    .setContext(errorContext)
                    .setServiceContext(ServiceContext.newBuilder().setService("gke_services").build())
                    .build();
            // Report an event synchronously, use .reportErrorEventCallable for asynchronous reporting.
            reportErrorsServiceClient.reportErrorEvent(projectName, customErrorEvent);
        }

but if your application running on GKE, Error Reporting is integrated with Google Kubernetes Engine, you must add the `cloud-platform` access scope.
        `gcloud container clusters create example-cluster-name --scopes 
        https://www.googleapis.com/auth/cloud-platform`
so whenever app is throwing an error it will shows in error reporting and service will be `gke_instances`

**References :**

- https://cloud.google.com/error-reporting/docs/setup/java

**Comment by hkothari** [comment] 2019-08-09 17:08
Is it possible to just globally override that `ServiceContext.newBuilder().setService("gke_services").build()`

I'm currently using the logging appender which forwards the errors to stackdriver. I don't think I can explicitly override the reportErrorEvent call (nor would I want to) I'd just like to override the string "gke_services"

**Comment by rgba** [comment] 2019-08-13 08:26
This might be the same issue as described in #5765

**Comment by codyoss** [comment] 2019-12-03 22:01
Closing this as a duplicate of #5765. The backend service is currently not exposing enough information to the client libraries to fill in namespace and container name. The issue is being tracked here: https://b.corp.google.com/issues/145009094

**Closed by codyoss** 2019-12-03 22:01 UTC
Labels: api: logging, type: question
