### ISSUE TITLE
@suztomo

### ISSUE THREAD

**Issue by ibrahimosman1127** [googleapis/google-cloud-java#10067] opened 2023-11-18 21:53 UTC
@suztomo 
![1697420955185](https://github.com/googleapis/google-cloud-java/assets/7116647/ee6f53e7-5e55-46a6-8fd8-b38a6117102c)
![1697420989429](https://github.com/googleapis/google-cloud-java/assets/7116647/d0101deb-1916-456c-baa0-6698e9445477)

_Originally posted by @Jon-Gaara in https://github.com/googleapis/google-cloud-java/issues/9964#issuecomment-1763605179_

**Comment by suztomo** [comment] 2023-11-20 03:33
This issue seems a duplicate of #9964 without description. Is this a mistake?

**Comment by diegomarquezp** [comment] 2023-11-20 22:38
> Is this a mistake?
I would say so, given the title of the issue. 

@ibrahimosman1127 please feel free to reopen it once it is reformulated with a title and text describing the issue if opening a new one was intended

**Closed by diegomarquezp** 2023-11-20 22:38 UTC
