### ISSUE TITLE
Misuses of cryptographic APIs

### ISSUE THREAD

**Issue by mhp0rtal** [googleapis/google-cloud-java#5648] opened 2019-07-02 17:20 UTC
Hi
The following lines have cryptographic API misuses. <br> File name => google-cloud-clients/google-cloud-core/src/main/java/com/google/cloud/testing/BaseEmulatorHelper.java: Line number => 465: API name => MessageDigest:<BR> File name => google-cloud-clients/google-cloud-core/src/main/java/com/google/cloud/testing/BaseEmulatorHelper.java: Line number => 457: API name => MessageDigest:First parameter (with value "MD5") should be any of {SHA-256, SHA-384, SHA-512}<BR>

**Comment by chingor13** [comment] 2019-07-08 16:30
Duplicate of #5650

**Closed by chingor13** 2019-07-08 16:30 UTC
Labels: :rotating_light:, triage me
