### ISSUE TITLE
Storage[doc-samples] : Spilt StorageSnippest one per file

### ISSUE THREAD

**Issue by athakor** [googleapis/google-cloud-java#7299] opened 2020-07-27 13:25 UTC
Split storage snippets such way that there is one snippet per file.

Example Code:
https://github.com/googleapis/google-cloud-java/blob/master/google-cloud-examples/src/main/java/com/google/cloud/examples/storage/snippets/StorageSnippets.java

~://cc @frankyn

**Comment by frankyn** [comment] 2020-07-27 16:24
@JesseLovelace has implemented this work AFAIU. 

@JesseLovelace please confirm before @athakor continue on this path.

**Comment by athakor** [comment] 2020-07-30 17:31
@frankyn these snippets is quite old and i guess it's not in the current standard doc sample format, kindly check the similar issue [here](https://github.com/googleapis/google-cloud-java/issues/5462).

@JesseLovelace  colud you please confirm on this path.

**Comment by athakor** [comment] 2020-08-13 15:18
@JesseLovelace gentle ping

**Comment by JesseLovelace** [comment] 2020-08-24 20:54
@frankyn, the work I did was to split only the scoped samples, which are the most viewed ones. There are still many samples in the big StorageSnippets file that haven't been split, they remained because they were not scoped as part of the sample gap project. Splitting the rest was intended to be a follow-up. 

However, a very great deal of the samples in that file are unpublished and will likely *never* be published, so the effort to split them could be a waste. I'd rather identify and delete the useless samples first before @athakor goes through the trouble of splitting them, but that's definitely deprioritized for now.

**Comment by frankyn** [comment] 2020-08-24 23:07
@athakor please don't move forward with this request until @JesseLovelace unblocks the open question raised.

**Comment by athakor** [comment] 2020-08-25 08:14
@JesseLovelace @frankyn Thanks for the clarification

**Comment by meredithslota** [comment] 2022-02-14 19:05
Clarifying a comment above — with the addition of "sample browser" and the snippet bot, any eligible samples are now published at least _somewhere_. So this clean-up work should still probably be done, but I'll leave it to the Storage team to identify when.

**Comment by meredithslota** [comment] 2022-05-04 15:39
The storage samples were all moved by @JesseLovelace in two phases: https://github.com/googleapis/java-storage/pull/1258 to copy samples over and https://github.com/googleapis/google-cloud-java/pull/7822 to delete them here. Closing.

**Closed by meredithslota** 2022-05-04 15:39 UTC
Labels: api: storage, type: docs, samples
