### ISSUE TITLE
[KafkaPubSubConnector] : Getting UNAVAILABLE: HTTP/2 error code: NO_ERROR and goes into retry loop forever

### ISSUE THREAD

**Issue by mglittleworld** [googleapis/google-cloud-java#3071] opened 2018-03-21 23:41 UTC
I am using https://github.com/GoogleCloudPlatform/pubsub/tree/master/kafka-connector for publishing messages to pubsub from kafka.
Running into the below issue and the publishing enters an infinite loop of retrying same batch of messages  and not recovering. 

`java.lang.RuntimeException: java.util.concurrent.ExecutionException: io.grpc.StatusRuntimeException: UNAVAILABLE: HTTP/2 error code: NO_ERROR`
	`Received Goaway `
       `session_timed_out `
		`at com.google.pubsub.kafka.sink.CloudPubSubSinkTask.flush(CloudPubSubSinkTask.java:293)
		at org.apache.kafka.connect.runtime.WorkerSinkTask.commitOffsets(WorkerSinkTask.java:192)
		at org.apache.kafka.connect.runtime.WorkerSinkTaskThread.iteration(WorkerSinkTaskThread.java:75)
		at org.apache.kafka.connect.runtime.WorkerSinkTaskThread.execute(WorkerSinkTaskThread.java:58)
		at org.apache.kafka.connect.util.ShutdownableThread.run(ShutdownableThread.java:82)`

**Comment by sduskis** [comment] 2018-12-05 20:20
This is likely an obsolete issue and would not reoccur if you upgraded the client. I'm closing this assuming that the issue is fixed.  If this is indeed still an issue, please reopen it.

**Closed by sduskis** 2018-12-05 20:20 UTC
Labels: api: pubsub, type: question
