### ISSUE TITLE
BigQuery OAuth error when query with Federated Data Source

### ISSUE THREAD

**Issue by NicolaSpreafico** [googleapis/google-cloud-java#2552] opened 2017-10-25 10:02 UTC
I have a BigQuery federated data source which load data from a Google Spreadsheet.
The provided code is running from App Engine standard application, Java8 runtime.

Here is a simple query: 
`SELECT field FROM project.dataset.table`

Performing a query to that table from my personal account using BigQuery browser (https://bigquery.cloud.google.com) works very fine

Using Java API I'm getting the following error
```
java.io.IOException: BigQueryError{reason=accessDenied, location=, message=Access Denied: BigQuery BigQuery: No OAuth token with Google Drive scope was found.}
```

Here is a sample of the code that is running (plase note that Drive scopes is not missing)
```
private static final List<String> SCOPES = Arrays.asList(BigqueryScopes.BIGQUERY, "https://www.googleapis.com/auth/drive.readonly");
GoogleCredentials credentials = GoogleCredentials.getApplicationDefault().createScoped(SCOPES);
BigQueryOptions options = BigQueryOptions.newBuilder().setCredentials(credentials).build();
BigQuery client = options.getService();

String statement = ...;
QueryJobConfiguration queryConfig = QueryJobConfiguration.newBuilder(statement).setUseLegacySql(Boolean.FALSE).build();
Job queryJob = client.create(JobInfo.newBuilder(queryConfig).setJobId(jobId).build());
queryJob.waitFor();

queryJob.getStatus().getError()
```
--------------------------------------------------

I tried using a service account json key, and the query works fine, it seems that problem is related on using ApplicationDefault credential.

This error occurs if I'm using version **0.25.0** of the library. 
Using version **0.20.0** works fine
```
<dependency>
            <groupId>com.google.cloud</groupId>
            <artifactId>google-cloud-bigquery</artifactId>
            <version>0.20.0-beta</version>
        </dependency>
```

**Comment by NicolaSpreafico** [comment] 2017-10-30 08:41
I tried each version one by one, here is the result:
**0.24.0-beta**: Error
**0.23.1-beta**: Error
**0.23.0-beta**: Error
**0.22.0-beta**: Works

**Comment by pongad** [comment] 2018-02-05 23:03
@NicolaSpreafico I tried to reproduce this issue and got slightly different error. I got `Not found: Files /gdrive/id/XXXXXXX`.

How are you authenticating? If you're authenticating with a service account key (like [this](https://cloud.google.com/docs/authentication/getting-started#setting_the_environment_variable)), I believe you have to give access to the email associated with the account key `name@project-id.iam.gserviceaccount.com`.

Due to age of the issue, I'll close this for now, but please reopen this doesn't solve the problem.

**Comment by pongad** [comment] 2018-02-07 00:33
I see. I'll keep investigating. Could you let us know if you're using Standard or Flexible?

**Comment by NicolaSpreafico** [comment] 2018-02-07 06:40
I'm using App Engine Std Java8

**Comment by pongad** [comment] 2018-02-18 22:46
I think I found the issue. `createScoped` only attaches the scope "if the credentials support scopes". Turns out, when we run to App Engine, the implementation of Credentials (`ComputeEngineCredentials`) does not support scopes.

@neozwu Do you know if there's a way around this?

**Comment by pongad** [comment] 2018-02-21 06:54
Also assigning @hzyi-google from today's discussion.

**Comment by neozwu** [comment] 2018-02-22 23:50
I don't really know a good workaround for this (manually constructing AppengineCredentials will only work if your code is in appengine request thread, plus it is not recommended to use appengine.api.* anymore). We should add support of scopes to ComputeEngineCredentials in auth lib.

**Comment by Tomczik76** [comment] 2018-09-24 23:52
I'm experiencing this issue as well, is there any eta on a fix?

**Comment by hzyi-google** [comment] 2018-09-25 00:15
It doesn't seem possible fix this issue since ComputeEngineCredentials is determined at the time an instance is created. But we may want to explicitly state that ComputeEngineCredentials.createScoped() is not supported in the auth library to let customers know the cause of the error.

**Comment by sduskis** [comment] 2018-12-04 20:15
@hzyi-google is there anything actionable in this repository?  If not, can this discussion be moved to the auth repo?

**Comment by hzyi-google** [comment] 2018-12-05 01:53
@sduskis Nothing is actionable here. Feel free to move it to the auth repo (though it seems there is nothing actionable in the auth repo either).

**Closed** 2019-01-10 14:21 UTC
Labels: api: bigquery, status: blocked, type: question
