### ISSUE TITLE
resumable uploads do not implement keep-alive correctly

### ISSUE THREAD

**Issue by srosenberg** [googleapis/google-cloud-java#3531] opened 2018-08-06 03:55 UTC
We have implemented a multi-threaded storage uploader which uses `BlobWriteChannel` per thread to upload a chunk of a local file.  (Once all chunks are uploaded, `compose` operation completes the transfer.)  Despite `keep-alive` being enabled, (http) connections are not re-used, requiring a rather expensive TLS handshake on _every_ subsequent (file) upload.

The problem lies in the current implementation of resumable uploads.  Each intermediate `PUT` request (corresponding to a chunk being uploaded), except the last one, will result in `308` response code (see [1]) and consequently `HttpResponse.disconnect` (see [2]).

Thus, the corresponding connection is closed, effectively requiring a new handshake for each intermediate chunk in the subsequent upload.

[1] https://cloud.google.com/storage/docs/json_api/v1/how-tos/resumable-upload
[2] https://github.com/google/google-http-java-client/blob/release-1.24.1/google-http-client/src/main/java/com/google/api/client/http/HttpRequest.java#L1074

**Comment by hzyi-google** [comment] 2018-08-06 16:39
This would require work in google-http-java-client. cc/ @chingor13

**Comment by chingor13** [comment] 2018-08-17 23:33
It looks like we can handle this upstream in google-cloud-storage. We can disable the throwing of the exception on a non success code by using [`HttpRequest#setThrowExceptionOnExecuteError`](https://github.com/google/google-http-java-client/blob/release-1.24.1/google-http-client/src/main/java/com/google/api/client/http/HttpRequest.java#L737) and handle the 308 response separately.

We don't really want to add special handling for 308 responses in the http client because 308s mean something different to other services and that library is for generic http requests.

**Comment by srosenberg** [comment] 2018-08-18 00:39
@chingor13 Makes sense; any chance this fix would make the next maintenance release? Thanks!

**Comment by srosenberg** [comment] 2019-01-15 16:54
@ajaaym The aforementioned issue occurs when running on oracle's jre `1.8`.  Conceivably, the implementation (of `disconnect`) may have changed going from `1.8` to `1.9`?

**Comment by ajaaym** [comment] 2019-01-15 20:05
@srosenberg just checked with 1.8, dont see disconnect actually closing underlying network connection. when disconnect is called http [here](http://hg.openjdk.java.net/jdk8/jdk8/jdk/annotate/484e16c0a040/src/share/classes/sun/net/www/protocol/http/HttpURLConnection.java#l2777) is always null which doesnt result in closing underlying network connection.

**Comment by srosenberg** [comment] 2019-01-15 21:34
@ajaaym Yes, this module is used for batched uploads into storage; each batch may take tens of seconds up to a small multiple of one minute (we throttle them).  I am fairly certain the (side)effect of `disconnect` is to shut down an existing socket; I verified this via `netstat` and `tcpdump` at the time.  I don't have a standalone repro. at this time but will put something together in the next day or two.

**Comment by ajaaym** [comment] 2019-01-16 17:00
@srosenberg by default connection cache cleaner thread clears the connection idle for more than 5 second. so when you send new request after 5 second it starts all over again. I was able to reproduce this behavior (with and without calling disconnect). see [here](https://github.com/frohoff/jdk8u-jdk/blob/master/src/share/classes/sun/net/www/http/KeepAliveCache.java#L122) keepAliveTimeout is returned 0 which results in using LIFETIME constant which is 5000ms.

**Comment by srosenberg** [comment] 2019-02-05 18:45
@ajaaym I don't see how to override the default behavior.  Any suggestions? We have background threads that periodically upload logs into storage; they are scheduled to run every 5 minutes and take ~3 minutes on average to finish, hence ~2 minutes of idling.  We'd need to set `keepAliveTimeout` to ~5 minutes to reduce the number of hard disconnects.

**Comment by ajaaym** [comment] 2019-02-05 19:15
@srosenberg there is no way to override this in jdk. Best bet here is to use [ApacheHttpTransport](https://github.com/googleapis/google-http-java-client/blob/master/google-http-client-apache/src/main/java/com/google/api/client/http/apache/ApacheHttpTransport.java). 
Apache client keeps the connection open indefinitely if Keep-Alive header is not present in the response. which is the case here. Link to [document](http://hc.apache.org/httpcomponents-client-ga/tutorial/html/connmgmt.html#d5e373). So default configuration should work fine. In case you need to configure client, you can build the HttpClient using HttpClientBuilder and pass in to constructor of ApacheHttpTransport.

**Comment by ajaaym** [comment] 2019-08-01 14:42
Closing this as [ApacheHttpTransport](https://github.com/googleapis/google-http-java-client/blob/master/google-http-client-apache/src/main/java/com/google/api/client/http/apache/ApacheHttpTransport.java) should resolve this.

**Closed by ajaaym** 2019-08-01 14:42 UTC
Labels: api: storage, type: feature request
